module.exports = {

  DestroyedReadable: require('./src/readable/DestroyedReadable'),
  IsPaused: require('./src/readable/IsPaused'),
  PausedReadable: require('./src/readable/PausedReadable'),
  PipedReadable: require('./src/readable/PipedReadable'),
  ReadableHighWaterMark: require('./src/readable/ReadableHighWaterMark'),
  ReadableWithCloseEvent: require('./src/readable/ReadableWithCloseEvent'),
  ReadableWithDataEvent: require('./src/readable/ReadableWithDataEvent'),
  ReadableWithEncoding: require('./src/readable/ReadableWithEncoding'),
  ReadableWithEndEvent: require('./src/readable/ReadableWithEndEvent'),
  ReadableWithErrorEvent: require('./src/readable/ReadableWithErrorEvent'),
  ReadableWithReadableEvent: require('./src/readable/ReadableWithReadableEvent'),
  ReadDataFromReadable: require('./src/readable/ReadDataFromReadable'),
  ResumedReadable: require('./src/readable/ResumedReadable'),
  UnpipedReadable: require('./src/readable/UnpipedReadable'),
  UnshiftedReadable: require('./src/readable/UnshiftedReadable'),
  WrappedReadable: require('./src/readable/WrappedReadable'),

  CorkedWritable: require('./src/writable/CorkedWritable'),
  DestroyedWritable: require('./src/writable/DestroyedWritable'),
  EndedWritable: require('./src/writable/EndedWritable'),
  UncorkedWritable: require('./src/writable/UncorkedWritable'),
  WritableHighWaterMark: require('./src/writable/WritableHighWaterMark'),
  WritableWithCloseEvent: require('./src/writable/WritableWithCloseEvent'),
  WritableWithDefaultEncoding: require('./src/writable/WritableWithDefaultEncoding'),
  WritableWithErrorEvent: require('./src/writable/WritableWithErrorEvent'),
  WritableWithFinishEvent: require('./src/writable/WritableWithFinishEvent'),
  WritableWithOneTimeDrainEvent: require('./src/writable/WritableWithOneTimeDrainEvent'),
  WritableWithPipeEvent: require('./src/writable/WritableWithPipeEvent'),
  WritableWithUnpipeEvent: require('./src/writable/WritableWithUnpipeEvent'),
  WrittenWritable: require('./src/writable/WrittenWritable'),

  // aliases for Streams, which are both Readable and Writable
  DestroyedStream: require('./src/readable/DestroyedReadable'),
  PausedStream: require('./src/readable/PausedReadable'),
  StreamHighWaterMark: require('./src/readable/ReadableHighWaterMark'),
  StreamWithCloseEvent: require('./src/readable/ReadableWithCloseEvent'),
  StreamWithDataEvent: require('./src/readable/ReadableWithDataEvent'),
  StreamWithEncoding: require('./src/readable/ReadableWithEncoding'),
  StreamWithEndEvent: require('./src/readable/ReadableWithEndEvent'),
  StreamWithErrorEvent: require('./src/readable/ReadableWithErrorEvent'),
  StreamWithReadableEvent: require('./src/readable/ReadableWithReadableEvent'),
  ReadDataFromStream: require('./src/readable/ReadDataFromReadable'),
  ResumedStream: require('./src/readable/ResumedReadable'),
  UnpipedStream: require('./src/readable/UnpipedReadable'),
  UnshiftedStream: require('./src/readable/UnshiftedReadable'),
  WrappedStream: require('./src/readable/WrappedReadable'),
  CorkedStream: require('./src/writable/CorkedWritable'),
  EndedStream: require('./src/writable/EndedWritable'),
  UncorkedStream: require('./src/writable/UncorkedWritable'),
  StreamWithDefaultEncoding: require('./src/writable/WritableWithCloseEvent'),
  StreamWithFinishEvent: require('./src/writable/WritableWithFinishEvent'),
  StreamWithOneTimeDrainEvent: require('./src/writable/WritableWithOneTimeDrainEvent'),
  StreamWithPipeEvent: require('./src/writable/WritableWithPipeEvent'),
  StreamWithUnpipeEvent: require('./src/writable/WritableWithUnpipeEvent'),
  StreamWritable: require('./src/writable/WrittenWritable')

}
